version: "3.0"

services:
  web:
    image: ioannisgiak89/grails:3.3.2
    environment:
      - RUN_APP=false
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - ./:/app
      - /home/ig657/.gradle:/home/grails/.gradle
      - /home/ig657/.m2:/home/grails/.m2
    links:
      - db:db.docker

  db:
    image:  ioannisgiak89/psql-york:9.5
    environment:
      - POSTGRES_PASSWORD=demo
      - POSTGRES_USER=liquibase_demo
      - POSTGRES_DB=liquibase_demo
      - SCHEMA=liquibase_demo
      - APPLICATION=app_liquibase_demo
      - APPLICATION_USER_PWD=demo2
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgres

volumes:
  dbdata:
    driver: local
